# API Keys for the YouTube Q&A Bot
HUGGING_FACE_API_KEY = ""
PINECONE_API_KEY = ""
PINECONE_ENVIRONMENT = ""  # The environment from your Pinecone host URL
GOOGLE_API_KEY = ""

# LangSmith Configuration
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""
LANGCHAIN_TRACING_V2 = "true"

GOOGLE_SEARCH_API_KEY = ""
GOOGLE_SEARCH_ENGINE_ID = ""

SERPAPI_KEY = ""

# Tavily API Key for Research Assistant
TAVILY_API_KEY = ""

